### ISSUE TITLE
Raspberry PI Camera not supported?

### ISSUE THREAD

**Issue by KarlBaumann** [Motion-Project/motion-docker#6]
Just to clarify, according to readme file, this image does not support Raspberry camera, right?

**Comment by steveneighbour** [comment]
it won't work without modifications i wouldn't expect, as we are not passing through the Pi camera.

You'd likely need to include picamera (+ dependencies) in the pip install lines within the docker file + pass through the camera in the docker run arguements (as a guess, add --device /dev/vchiq)

**Comment by Letme** [comment]
The image deployed is for x86 only, so I think we need someone to build for multiple platforms. Since it is done offline by someone (not in CI) I cant really contribute, but solution is simple by just adding `--platform` flag to the build command (experimental enabled):

```
docker buildx build --platform linux/arm32v7, linux/arm64v8, ...
```

**Comment by tosiara** [comment]
What image are you referencing?

**Comment by Letme** [comment]
https://hub.docker.com/r/motionproject/motion/tags

**Comment by tosiara** [comment]
Are there other ways to build more architectures without `buildx` and experimental features?

**Comment by Letme** [comment]
If you build it on raspberry pi then its natively built for other architecture. That's how we were doing it before.

**Comment by tosiara** [comment]
Would you like try? I have pushed some build to my personal docker hub:
```
tosiara/motion:amd64
tosiara/motion:arm32
tosiara/motion:arm64
```
https://hub.docker.com/repository/registry-1.docker.io/tosiara/motion/tags
Is this you were looking for?

**Comment by Letme** [comment]
Docker now reports the correct platform, but the images still fail to execute on arm with "exec format error" . I was fishing around for a solution a bit and I am looking at ubuntu (thought that doesnt pick the correct arch to start building your image from) and they have a bit different platform denominators like you. Can you maybe copy one of those (https://hub.docker.com/_/ubuntu?tab=tags)? `linux/arm64/v8` `linux/arm/v7`

Side note: images can have same name - docker will automatically separate them and serve a proper image for proper platform.

**Comment by tosiara** [comment]
Which raspberry are you using?

**Comment by Letme** [comment]
I am testing this on 4.

**Comment by tosiara** [comment]
`exec format error` happens when you try to run 64 bit on a 32 bit platform. Were you specifically trying to run `tosiara/motion:arm64`?

**Comment by tosiara** [comment]
```
motion@ubuntu:~$ sudo docker pull tosiara/motion:arm64
[sudo] password for motion: 
arm64: Pulling from tosiara/motion
68fe03cb170d: Pull complete 
18959295effb: Pull complete 
51118fb70ce3: Pull complete 
409a5d9eae93: Pull complete 
b97305fb8a69: Pull complete 
d63d00a3c64e: Pull complete 
Digest: sha256:f8d7c84774339e2cd55c4e4bd861b39277c1b8ba95896e3bff48313a802b5437
Status: Downloaded newer image for tosiara/motion:arm64
docker.io/tosiara/motion:arm64
motion@ubuntu:~$ sudo docker run tosiara/motion:arm64
standard_init_linux.go:211: exec user process caused "exec format error"
motion@ubuntu:~$ uname -a
Linux ubuntu 4.15.0-96-generic-lpae #97-Ubuntu SMP Wed Apr 1 05:29:00 UTC 2020 armv7l armv7l armv7l GNU/Linux
```

**Comment by Letme** [comment]
Great, now it works. Indeed it is armv7l and not how I thought armhf. I can now access my USB camera using `--device` input inside docker container.

**Comment by tosiara** [comment]
Can you provide more details, how do you pass usb camera into docker on your Pi? This will be useful for other users

**Comment by Letme** [comment]
Like I said, using the `--device` you can pass that. So for example if you have stream port of 8081 and webinterface at 8080 in config (which per motion installation it should be in `~/.motion/motion.conf`) and you want to record videos to the `/home/pi/movies` directory (in config you need to have `/movies`) then its a below command:

```
docker run -d --name=motion \
           -p 8080:8080 -p 8081:8081 \
           -e TZ="Europe/Brussels" \
           -v /home/pi/.motion:/usr/local/etc/motion \
           -v /home/pi/movies:/movies \
           --device /dev/video0 \
           tosiara/motion:arm32
```

If I find some time I will try to make this Kubernetes friendly (with conf converted with ConfigMAp and movies storage as persistent storage (although how to download this is still a bit of enigma if there are many pods).
